services:
  frontend:
    image: frontend-nodejs
    build: ./frontend/
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: backend-springboot
    build: ./backend/
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db-postgresql:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db-postgresql

  db-postgresql:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    shm_size: ${POSTGRES_SHM_SIZE}
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: ${POSTGRES_TMPFS_SIZE}
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"